perspective_transform:
  max_x: 10
  max_y: 10
  max_z: 5

blur:
  enable: true
  fraction: 0.1

prydown:
  enable: true
  fraction: 0.3

noise:
  enable: true
  fraction: 0.3

  gauss:
    enable: true
    fraction: 0.3

  uniform:
    enable: true
    fraction: 0.3

  salt_pepper:
    enable: true
    fraction: 0.1

  poisson:
    enable: true
    fraction: 0.3

line:
  enable: true
  fraction: 0.3

  under_line:
    enable: true
    fraction: 0.5

  table_line:
    enable: true
    fraction: 0.4

  middle_line:
    enable: true
    fraction: 0.1

